require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/*/db/schema.rb'

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - '**/db/migrate/*'

Rails/DynamicFindBy:
  Exclude:
    - lib/can_can_dry/ability_mapping.rb

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
