---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Gemspec/DeprecatedAttributeAssignment:
  Exclude:
  - can_can_dry.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
  - can_can_dry.gemspec
Layout/LineEndStringConcatenationIndentation:
  Exclude:
  - lib/can_can_dry/ability_mapping/action_mapping_not_found.rb
Lint/RedundantCopDisableDirective:
  Exclude:
  - app/helpers/can_can_dry_helper.rb
Rails/EagerEvaluationLogMessage:
  Exclude:
  - lib/can_can_dry/path_recognizer.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - lib/tasks/can_can_dry.rake
  - spec/lib/can_can_dry/path_recognizer_spec.rb
  - spec/lib/rubocop_check_spec.rb
  - spec/spec_helper.rb
Style/RedundantReturn:
  Exclude:
  - lib/can_can_dry/ability_mapping.rb
